name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

<<<<<<< HEAD
    - name: Build and Push Docker Image 
      uses: docker/build-push-action@v5   
=======
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
>>>>>>> 8d2e58a1fc725454b275ad5fd9da30ff062e4f39
      with:
        context: .
        push: true
        tags: | 
<<<<<<< HEAD
          ghcr.io/${{github.repository_owner | toLowerCase}}/getting-started:latest
          ghcr.io/${{github.repository_owner | toLowerCase}}/getting-started:${{github.sha}}
=======
          ghcr.io/${{ github.repository_owner }}/ahmedmahmoudabuzaidd/getting-started:latest
          ghcr.io/${{ github.repository_owner }}/ahmedmahmoudabuzaidd/getting-started:${{ github.sha }}
>>>>>>> 8d2e58a1fc725454b275ad5fd9da30ff062e4f39
